export const PRODUCTS = ["PGH", "Factoring", "Gestora", "Cambio Seguro", "Tandia"];
export const TYPES = ["Tipo de entregable", "Research", "Pruebas de usabilidad"];
export const ESTADOS = ["Persona asignada", "Ana R.", "Sofia K.", "Luis M.", "Carlos T."];
export const STATUSES = ["Borrador", "Publicado"];
export const TEAM_MEMBERS = ["Ana R.", "Sofia K.", "Luis M.", "Carlos T."];
export const METODOLOGIAS = ["Cualitativa", "Cuantitativa", "Mixta", "Desk Research"];
export const JIRA_STATUSES = ["EN CURSO", "FINALIZADO"];

export const NAV = [
  { label: "Entregables", icon: "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4", active: true },
];

export const TYPE_COLORS = { "Research": "amber", "Otros entregables": "violet", "Pruebas de usabilidad": "blue", "Buyer Persona": "green" };

export const PRODUCT_COLORS = {
  "PGH": "#00D97A",
  "Factoring": "#00975B",
  "Gestora": "#004D2E",
  "Tandia": "#1D4ED8",
  "Cambio Seguro": "#7C3AED",
};

export const avatarPalette = [
  { l: "bg-green-100 text-green-700", d: "bg-green-900 text-green-300" },
  { l: "bg-blue-100 text-blue-700", d: "bg-blue-900 text-blue-300" },
  { l: "bg-pink-100 text-pink-700", d: "bg-pink-900 text-pink-300" },
  { l: "bg-teal-100 text-teal-700", d: "bg-teal-900 text-teal-300" },
];

export const INITIAL_DELIVERABLES = [
  {
    id: 1,
    title: "Buyer, User y Arquetipos",
    type: "Research",
    typeColor: "amber",
    date: "Nov 06, 2025",
    metodologia: "Cualitativa",
    jira: "UX-2095: TANDIA: PC10 Roadmap del Us. en Buyer y Arquetipos de un producto",
    jiraStatus: "FINALIZADO",
    team: ["Cristian G."],
    tags: ["Tandia"],
    objetivo: "Definir el Buyer Persona, User Persona y Arquetipos de Tandia.",
    usuario: "Clientes activos de Tandia de los meses de Julio a Setiembre pertenecientes a los tres planes: facturador, pyme y full. Se realizó una separación en dos grupos: Dueños de negocio (enfocados al Buyer y User en ciertos casos) y Personal del negocio (enfocado en el User).",
    hallazgos: "Para los dueños de negocio, se identificaron 3 Buyer Persona y 3 arquetipos. El riesgo es transversal a todos los negocios, sin embargo, los dueños buscan formas de mitigar ese riesgo. Una de esas formas es teniendo orden e información sobre su emprendimiento. Sin negocio, los clientes son organismos vivos, donde su necesidad de orden e información va evolucionando.",
    status: "Publicado",
    archivo: "Buyer, User y Arquetipos — Presentación.pdf",
  },
  {
    id: 2,
    title: "Motivos de abandono y valor percibido",
    type: "Research",
    typeColor: "amber",
    date: "Jul 11, 2025",
    metodologia: "Mixta",
    jira: "UX-1710: TANDIA: Valor percibido por clientes activos",
    jiraStatus: "FINALIZADO",
    team: ["Cristian G."],
    tags: ["Tandia"],
    objetivo: "Conocer los aspectos más valorados de los clientes sobre la plataforma de Tandia, los motivos por los cuales los clientes han decidido dejar de usar el producto, y tomar decisiones en torno a la continuidad y desarrollo del producto.",
    usuario: "Clientes de Tandia activos en el último año y clientes que cesaron su contrato en el último año.",
    hallazgos: "Si bien el 89% de comentarios rescatados perciben valor en la rapidez y facilidad de uso de la plataforma, la mayoría de los usuarios solo le dan uso a los módulos de Clientes, Productos y Ventas. El 45% de los motivos de abandono están relacionados con la insatisfacción con la plataforma y que los aspectos de mejora están relacionados a aspectos que van más allá de esa funcionalidad.",
    status: "Publicado",
    archivo: "Presentación — Motivos de abandono y Valor percibido.pdf",
  },
  {
    id: 3,
    title: "Gestión de roles",
    type: "Research",
    typeColor: "amber",
    date: "May 07, 2025",
    metodologia: "Cuantitativa",
    jira: "UX-1523: Gestión de roles y funcionalidad de Tandia",
    jiraStatus: "FINALIZADO",
    team: ["Cristian G."],
    tags: ["Tandia"],
    objetivo: "Validar el interés de clientes de Tandia en poder gestionar los permisos y accesos de los roles por su cuenta.",
    usuario: "Clientes de Tandia en planes PYME.",
    hallazgos: "La funcionalidad de cambiar los roles de manera autónoma es un nice-to-have: puede ser algo deseable, pero no es esencial según sus necesidades. Hay posibilidad de enfocarse en los puntos de mejora mencionados por los clientes, los cuales impactan en el uso diario de la plataforma.",
    status: "Publicado",
    archivo: "Research — Gestión de roles.pdf",
  },
  {
    id: 4,
    title: "Flujo de solicitud — Crédito hipotecario",
    type: "Pruebas de usabilidad",
    typeColor: "blue",
    date: "Feb 14, 2025",
    metodologia: "Cualitativa",
    jira: "UX-1840: Flujo solicitud crédito hipotecario",
    jiraStatus: "FINALIZADO",
    team: ["Ana R.", "Luis M."],
    tags: ["Créditos Hipotecarios"],
    objetivo: "Evaluar el flujo de solicitud de crédito hipotecario e identificar fricciones en el proceso de validación de identidad.",
    usuario: "Personas naturales entre 28 y 55 años con intención de adquirir un crédito hipotecario en los próximos 6 meses.",
    hallazgos: "Se detectaron fricciones en el paso de validación de identidad. 3 de 8 participantes no completaron el flujo sin asistencia. La pantalla de confirmación genera confusión respecto al siguiente paso.",
    status: "Publicado",
    archivo: "Prueba de usabilidad — Crédito hipotecario.pdf",
  },
  {
    id: 5,
    title: "Research — Experiencia de onboarding deudores",
    type: "Research",
    typeColor: "amber",
    date: "Dic 03, 2024",
    metodologia: "Cualitativa",
    jira: "UX-1692: Onboarding deudores Recadia",
    jiraStatus: "FINALIZADO",
    team: ["Luis M.", "Carlos T."],
    tags: ["Recadia"],
    objetivo: "Comprender la experiencia de primer contacto y proceso de registro de deudores en la plataforma Recadia.",
    usuario: "Deudores que recibieron una notificación de cobranza en los últimos 3 meses y accedieron por primera vez a la plataforma.",
    hallazgos: "El 70% de los participantes no entendió el propósito de la plataforma en el primer acceso. El lenguaje legal genera ansiedad. La falta de información sobre el proceso completo es el principal punto de abandono.",
    status: "Publicado",
    archivo: "Research — Onboarding deudores.pdf",
  },
  {
    id: 6,
    title: "Buyer Persona — Segmento PYME",
    type: "Buyer Persona",
    typeColor: "green",
    date: "Nov 21, 2024",
    metodologia: "Mixta",
    jira: "UX-1600: Buyer Persona PYME — Préstamos Hipotecarios",
    jiraStatus: "FINALIZADO",
    team: ["Sofia K.", "Carlos T.", "Ana R."],
    tags: ["Préstamos con Garantía Hipotecaria"],
    objetivo: "Definir el perfil del cliente PYME que solicita financiamiento con garantía hipotecaria.",
    usuario: "Dueños de PYME que han solicitado o evaluado un préstamo con garantía hipotecaria en el último año.",
    hallazgos: "Se identificaron 2 perfiles principales: el empresario consolidado que busca expansión y el empresario en crisis que busca liquidez. Ambos perfiles valoran la rapidez y la claridad en las condiciones del préstamo por encima de la tasa de interés.",
    status: "Publicado",
    archivo: "Buyer Persona — Segmento PYME.pdf",
  },
  {
    id: 7,
    title: "Benchmark — Plataformas tipo de cambio digital",
    type: "Otros entregables",
    typeColor: "violet",
    date: "Ago 05, 2024",
    metodologia: "Desk Research",
    jira: "UX-1450: Benchmark Cambio Seguro",
    jiraStatus: "FINALIZADO",
    team: ["Carlos T."],
    tags: ["Cambio Seguro"],
    objetivo: "Analizar las principales plataformas de tipo de cambio digital para identificar oportunidades de diferenciación.",
    usuario: "No aplica — investigación de escritorio.",
    hallazgos: "Se analizaron 6 plataformas competidoras. Las principales oportunidades de diferenciación están en la transparencia de comisiones, la velocidad de transferencia y las notificaciones en tiempo real. Ningún competidor ofrece historial de operaciones exportable.",
    status: "Publicado",
    archivo: "Benchmark — Tipo de cambio digital.pdf",
  },
  {
    id: 8,
    title: "Research — Perfil del arrendatario digital",
    type: "Research",
    typeColor: "amber",
    date: "Jun 14, 2024",
    metodologia: "Cualitativa",
    jira: "UX-1380: Perfil arrendatario Tandia API",
    jiraStatus: "EN CURSO",
    team: ["Sofia K."],
    tags: ["Tandia API"],
    objetivo: "Explorar los modelos mentales y expectativas de arrendatarios que utilizan plataformas digitales por primera vez.",
    usuario: "Arrendatarios de locales comerciales entre 25 y 45 años que han comenzado a usar herramientas digitales de gestión en el último año.",
    hallazgos: "Los arrendatarios priorizan la simplicidad sobre la funcionalidad avanzada. El principal temor es perder el control de la información de sus clientes. La integración con herramientas conocidas (WhatsApp, email) es clave para la adopción.",
    status: "En revisión",
    archivo: "Research — Perfil arrendatario digital.pdf",
  },
  {
    id: 9,
    title: "Journey Map — Inversionista primera inversión",
    type: "Otros entregables",
    typeColor: "violet",
    date: "Ene 10, 2025",
    metodologia: "Cualitativa",
    jira: "UX-1750: Journey Map Gestora de Fondos",
    jiraStatus: "FINALIZADO",
    team: ["Sofia K.", "Ana R."],
    tags: ["Gestora de Fondos"],
    objetivo: "Mapear el proceso completo del inversionista desde el primer contacto hasta la confirmación de su primera inversión.",
    usuario: "Personas naturales con capital disponible para invertir que nunca han usado una gestora de fondos digital.",
    hallazgos: "El proceso de KYC (Know Your Customer) es el principal punto de abandono. Los inversionistas necesitan confirmación constante de que su dinero está seguro. La falta de un resumen claro del producto antes de invertir genera desconfianza.",
    status: "Publicado",
    archivo: "Journey Map — Primera inversión.pdf",
  },
  { id: 10, title: "Research — Nuevas funcionalidades Factoring", type: "Research", typeColor: "amber", date: "Mar 01, 2026", metodologia: "Cualitativa", jira: "UX-2210: Factoring nuevas funcionalidades", jiraStatus: "EN CURSO", team: ["Ana R."], tags: ["Factoring"], objetivo: "Explorar las necesidades de los clientes actuales respecto a nuevas funcionalidades del módulo de factoring.", usuario: "Clientes activos del módulo Factoring con más de 6 meses de uso.", hallazgos: "Investigación en curso.", status: "Borrador", archivo: "Research — Factoring funcionalidades.pdf" },
  { id: 11, title: "Buyer Persona — Segmento millennials Cambio Seguro", type: "Buyer Persona", typeColor: "green", date: "Feb 20, 2026", metodologia: "Mixta", jira: "UX-2198: Buyer Persona Cambio Seguro millennials", jiraStatus: "EN CURSO", team: ["Sofia K.", "Carlos T."], tags: ["Cambio Seguro"], objetivo: "Definir el perfil del cliente millennial que utiliza plataformas de tipo de cambio digital.", usuario: "Personas entre 25 y 35 años que realizan operaciones de cambio de divisas al menos una vez al mes.", hallazgos: "En proceso de análisis.", status: "Borrador", archivo: "Buyer Persona — Cambio Seguro millennials.pdf" },
];
